### ISSUE TITLE
org.xml.sax.helpers.LocatorImpl not serializable when transforming a PMML file to an SER file

### ISSUE THREAD

**Issue by chenguangshen** [jpmml/jpmml-model#10]
Based on the example of `jpmml-android` I am trying to evaluate a few PMML models generated by `sklearn2pmml`. Since I am using Android Studio + gradle, I cannot really use the maven plugin to transform PMML files to SER files. So I created a bare-bone Java program based on https://github.com/jpmml/jpmml-model/blob/master/pmml-maven-plugin/src/main/java/org/jpmml/model/plugin/SerMojo.java and https://github.com/jpmml/jpmml-android/blob/master/pmml-android-example/pom.xml:
```
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import javax.xml.transform.Source;

import org.dmg.pmml.PMML;
import org.jpmml.model.ImportFilter;
import org.jpmml.model.JAXBUtil;
import org.jpmml.model.SerializationUtil;
import org.jpmml.model.visitors.StringInterner;
import org.xml.sax.InputSource;

public class PMMLTransformer {
    private final static String BASE_PATH = "./";

    public static void main(String[] args) throws Exception {
        File pmmlFile = new File(BASE_PATH + "/model.pmml");
        File serFile = new File(BASE_PATH + "/model.pmml.ser");

        // Parse a pmml object from a file
        PMML pmml;
        try (InputStream is = new FileInputStream(pmmlFile)) {
            Source source = ImportFilter.apply(new InputSource(is));
            pmml = JAXBUtil.unmarshalPMML(source);
        }

        // Apply a visitor
        StringInterner visitor = new StringInterner();
        visitor.applyTo(pmml);

        // Write an ser file from the pmml object
        try (OutputStream os = new FileOutputStream(serFile)) {
            SerializationUtil.serializePMML(pmml, os);
        }
    }
}
```

Which generates an Exception on serialization:
```
Exception in thread "main" java.io.NotSerializableException: org.xml.sax.helpers.LocatorImpl
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.jpmml.model.SerializationUtil.serialize(SerializationUtil.java:57)
	at org.jpmml.model.SerializationUtil.serializePMML(SerializationUtil.java:43)
	at edu.ucla.nesl.toolkit.pmmltransformer.PMMLTransformer.main(PMMLTransformer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1
```

Both `jpmml-model` and `jpmml-evaluator` are on 1.3.3

Any suggestions? Thanks!

**Comment by chenguangshen** [comment]
I tried transforming the models using the maven plugin. It did not give me the same error but nevertheless failed because of the seemingly incompatible PMML format:
```
[ERROR] Failed to execute goal org.jpmml:pmml-maven-plugin:1.2.13:ser (default) on project pmml-android-example: Failed to process model dt_depth5.pmml: http://www.dmg.org/PMML-4_3 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jpmml:pmml-maven-plugin:1.2.13:ser (default) on project pmml-android-example: Failed to process model dt_depth5.pmml
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to process model dt_depth5.pmml
	at org.jpmml.model.plugin.SerMojo.transform(SerMojo.java:171)
	at org.jpmml.model.plugin.SerMojo.execute(SerMojo.java:132)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalArgumentException: http://www.dmg.org/PMML-4_3
	at org.jpmml.schema.Version.forNamespaceURI(Version.java:61)
	at org.jpmml.model.PMMLFilter.updateSource(PMMLFilter.java:121)
	at org.jpmml.model.PMMLFilter.startPrefixMapping(PMMLFilter.java:43)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startNamespaceMapping(AbstractSAXParser.java:2164)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:469)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:379)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:605)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3138)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
	at org.jpmml.model.JAXBUtil.unmarshal(JAXBUtil.java:54)
	at org.jpmml.model.JAXBUtil.unmarshalPMML(JAXBUtil.java:40)
	at org.jpmml.model.plugin.SerMojo.transform(SerMojo.java:182)
	at org.jpmml.model.plugin.SerMojo.transform(SerMojo.java:169)
	... 23 more
```

The models generated using `sklearn2pmml` include:
- `sklearn.tree.DecisionTreeClassifier`
- `sklearn.ensemble.RandomForestClassifier`
- `sklearn.svm.SVC`

**Comment by chenguangshen** [comment]
Solved: I used the solution suggested by http://stackoverflow.com/questions/35459942/resolve-sparkexception-task-not-serializable-when-importing-pmml-model and applied a `LocatorNullifier` to the pmml:
```
LocatorNullifier locatorNullifier = new LocatorNullifier();
locatorNullifier.applyTo(pmml);
```

Also version 1.3.3 works well with the PMML 4.3 generated by `sklearn2pmml`.

Thanks again for your pointer in the other thread @vruusmann
