### ISSUE TITLE
IllegalAccessError while parsing PMML File 

### ISSUE THREAD

**Issue by mackaiver** [jpmml/jpmml-model#11]
Hello,

I'm trying to build a RapidMiner extension to read PMML models. 
However I'm getting the following exception when unmarshaling a pmml file:

```
java.lang.IllegalAccessError: Class com.sun.xml.internal.bind.v2.runtime.reflect.Accessor$FieldReflection can not access a member of class org.dmg.pmml.PMML with modifiers "private"
	at com.sun.xml.internal.bind.v2.runtime.reflect.Accessor$FieldReflection.set(Accessor.java:262)
	at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:230)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:195)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at org.jpmml.model.PMMLFilter.startElement(PMMLFilter.java:69)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
	at org.jpmml.model.JAXBUtil.unmarshal(JAXBUtil.java:78)
	at org.jpmml.model.JAXBUtil.unmarshalPMML(JAXBUtil.java:64)
	at org.jpmml.model.PMMLUtil.unmarshal(PMMLUtil.java:34)
	at de.woistbier.rapidminer.pmml.operator.PMMLEvaluator.read(PMMLEvaluator.java:118)
	at de.woistbier.rapidminer.pmml.operator.PMMLEvaluator.read(PMMLEvaluator.java:34)
	at com.rapidminer.operator.io.AbstractReader.doWork(AbstractReader.java:126)
	at com.rapidminer.operator.Operator.execute(Operator.java:1005)
	at com.rapidminer.operator.execution.SimpleUnitExecutor.execute(SimpleUnitExecutor.java:77)
	at com.rapidminer.operator.ExecutionUnit$3.run(ExecutionUnit.java:812)
	at com.rapidminer.operator.ExecutionUnit$3.run(ExecutionUnit.java:807)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.rapidminer.operator.ExecutionUnit.execute(ExecutionUnit.java:807)
	at com.rapidminer.operator.OperatorChain.doWork(OperatorChain.java:428)
	at com.rapidminer.operator.Operator.execute(Operator.java:1005)
	at com.rapidminer.Process.run(Process.java:1205)
	at com.rapidminer.Process.run(Process.java:1101)
	at com.rapidminer.Process.run(Process.java:1054)
	at com.rapidminer.Process.run(Process.java:1049)
	at com.rapidminer.Process.run(Process.java:1039)
	at com.rapidminer.gui.ProcessThread.run(ProcessThread.java:65)
```  
This might be general problem when having restrictive security managers. So maybe making some fields in `class org.dmg.pmml.PMML` public could help.
Any other ideas?

**Comment by vruusmann** [comment]
What are your JDK and JPMML-Model library versions? How is your build configured, are you including `org.jpmml:pmml-model` dependency, or the `org.jpmml:pmml-model-metro` dependency?

> So maybe making some fields in class org.dmg.pmml.PMML public could help.

That would be a bad thing to do.

Anyway, you can relax the visibility of PMML class model fields in your application code using Java reflection API.

Something like this:
```java
java.lang.reflect.Field[] fields = PMML.class.getDeclaredFields();
for(java.lang.reflect.Field field : fields){
	field.setAccessible(true);
}
```

You would need to do it before invoking the `PMMLUtil#unmarshal(InputStream)` method.

**Comment by vruusmann** [comment]
Also, could be the case that RapidMiner uses some custom classloading mechanism, which interferes with JAXB unmarshaller. Can you parse the PMML file using a command-line application?

**Comment by mackaiver** [comment]
> Also, could be the case that RapidMiner uses some custom classloading mechanism, which 
> interferes with JAXB unmarshaller. Can you parse the PMML file using a command-line application?

It works fine from the command line. 

> Something like this:
> 
>```
>java.lang.reflect.Field[] fields = PMML.class.getDeclaredFields();
>for(java.lang.reflect.Field field : fields){
>	field.setAccessible(true);
>}
>```
> You would need to do it before invoking the PMMLUtil#unmarshal(InputStream) method.

This doesn't work because of the security manager I guess. It produces a `java.security.AccessControlException`

```
java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.rapidminer.security.PluginSecurityManager.checkPermission(PluginSecurityManager.java:27)
	at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:128)
	at de.woistbier.rapidminer.pmml.operator.PMMLEvaluator.read(PMMLEvaluator.java:120)
	at de.woistbier.rapidminer.pmml.operator.PMMLEvaluator.read(PMMLEvaluator.java:34)
	at com.rapidminer.operator.io.AbstractReader.doWork(AbstractReader.java:126)
	at com.rapidminer.operator.Operator.execute(Operator.java:1005)
	at com.rapidminer.operator.execution.SimpleUnitExecutor.execute(SimpleUnitExecutor.java:77)
	at com.rapidminer.operator.ExecutionUnit$3.run(ExecutionUnit.java:812)
	at com.rapidminer.operator.ExecutionUnit$3.run(ExecutionUnit.java:807)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.rapidminer.operator.ExecutionUnit.execute(ExecutionUnit.java:807)
	at com.rapidminer.operator.OperatorChain.doWork(OperatorChain.java:428)
	at com.rapidminer.operator.Operator.execute(Operator.java:1005)
	at com.rapidminer.Process.run(Process.java:1205)
	at com.rapidminer.Process.run(Process.java:1101)
	at com.rapidminer.Process.run(Process.java:1054)
	at com.rapidminer.Process.run(Process.java:1049)
	at com.rapidminer.Process.run(Process.java:1039)
	at com.rapidminer.gui.ProcessThread.run(ProcessThread.java:65)
```

**Comment by vruusmann** [comment]
If it works from command-line, and not from within RapidMiner, then you should contact the RapidMiner team for technical assistance.

Most probably, RapidMiner's security manager is also preventing JAXB unmarshaller from doing its work - it should be the case that Sun/Oracle JAXB engine also uses Java reflection APIs to map XML and Java data structures.

The original JAXB error message is also an `java.lang.IllegalAccessError`. It's thrown when a Java field could is not accessible, for example when the `Field#setAccessible(true)` was invoked, but didn't have any effect (in this case, the JAXB engine probably quitely swallowed the intermediate `java.security.AccessControlException`).

**Comment by vruusmann** [comment]
Another idea - maybe there is some Apache Maven plugin that can rewrite JPMML-Model classes (during the packaging phase of the build) by changing all field access modifiers from `private` to `public`.

This way the JPMML-Model library could stay as it is, and you could still have your "tweaked" variant of it.

**Comment by 0xcfe4f1** [comment]
> Another idea - maybe there is some Apache Maven plugin that can rewrite JPMML-Model classes (during the packaging phase of the build) by changing all field access modifiers from `private` to `public`.
> 
> This way the JPMML-Model library could stay as it is, and you could still have your "tweaked" variant of it.

Villu, your intuition here is correct, thank you for the hint.

I recently experienced this exact problem when trying to unmarshall PMML XML files at runtime with JAXB via [org.jpmml.model.PMMLUtil.unmarshal(...)](https://github.com/jpmml/jpmml-model/blob/master/pmml-model/src/main/java/org/jpmml/model/PMMLUtil.java#L27) on a JVM with a very restrictive security policy in place.

I solved the problem by modifying the Maven POM build of my project with the following plugins:
- [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/examples/unpacking-artifacts.html) - In the [process-classes](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) phase, configure this plugin to unpack the `org.jpmml:pmml-model` JAR dependency to the project `target/classes` path (required for the plugin below to manipulate the bytecode, as it can't reach inside JARs); 
- https://github.com/hielkehoeve/maven-javassist - In the [process-classes](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) phase, apply a custom [Javassist](https://github.com/jboss-javassist/javassist) transformer over classes in the `org.dmg.pmml` package to transform all declared field modifiers from protected/private to public (see below for my Javassist transformer implementation, `MyClassTransformer`);
- [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/) - In the [package](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) phase, construct a JAR by excluding any `org.jpmml:pmml-model` dependencies except those which were modified by the Javassist plugin above.

After packaging my code with this build configuration, JAXB successfully unmarshalls PMML XML at runtime without the exception above _(java.lang.IllegalAccessError: Class com.sun.xml.internal.bind.v2.runtime.reflect.Accessor$FieldReflection can not access a member of class org.dmg.pmml.PMML with modifiers "private")_.    

The Javassist transformer implementation was straightforward:
```
import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtField;
import javassist.Modifier;
import nl.topicus.plugins.maven.javassist.ClassTransformer;
import nl.topicus.plugins.maven.javassist.TransformationException;

public class MyClassTransformer extends ClassTransformer {
  @Override
  public void applyTransformations(ClassPool pool, CtClass clazz) throws TransformationException {
    for(CtField f : clazz.getDeclaredFields()) {
      f.setModifiers(Modifier.setPublic(f.getModifiers()));
    }
  }
}
```
One final hurdle was to permit Maven to find `MyClassTransformer` on the classpath when executing the plugin. I did this simply by using `mvn install` on a separate Maven project which packaged `MyClassTransformer` into its own `group:artifact` and added as a new dependency to my main project where the plugin is called.

**Comment by vruusmann** [comment]
> One final hurdle was to permit Maven to find MyClassTransformer on the classpath when executing the plugin.

@0xcfe4f1 Apache Maven plugins can declare their own "locally scoped" dependencies. For example, see https://github.com/jpmml/jpmml-model/blob/master/pmml-model/pom.xml#L195-L201
