### ISSUE TITLE
NoClassDefFoundError when using ImportFilter method.

### ISSUE THREAD

**Issue by aminaaslam** [jpmml/jpmml-model#7]
I am getting this error while running this piece of code. I am not sure as how to resolve it. Please help me.

try{ 
			
		   InputStream is = new FileInputStream(file); 
		  

		   
		   Source transformedSource = ImportFilter.apply(new InputSource(is));

		   pmml=JAXBUtil.unmarshalPMML(transformedSource);

	   } catch( Exception e) {
	      System.out.println( e.toString() );
	      throw e;
	   }
	   
	}

java.lang.NoClassDefFoundError: org/jpmml/schema/Version
	at com.norkorm.blake.pmml.LinearRegressionPMMLTest.loadModel(LinearRegressionPMMLTest.java:330)
	at com.norkorm.blake.pmml.LinearRegressionPMMLTest.testLinearPMML(LinearRegressionPMMLTest.java:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.jpmml.schema.Version
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 21 more

**Comment by vruusmann** [comment]
Class `org.jpmml.schema.Version` is contained in the `pmml-schema` module JAR file. You need to add this JAR file to your application classpath.

Here's an appropriate Apache Maven dependency declaration:
```xml
<dependency>
	<groupId>org.jpmml</groupId>
	<artifactId>pmml-schema</artifactId>
	<version>${jpmml.version}</version>
</dependency>
```

Let me guess - you're not using Apache Maven in your project? If you were, then the main `pmml-model` module JAR file would automatically download this extension `pmml-schema` module JAR file, because it is listed as a "hard" compile- and run-time dependency.

As a temporary workaround, you can manually download `pmml-schema` module JAR file from the Maven Central repository: http://repo1.maven.org/maven2/org/jpmml/pmml-schema/
