### ISSUE TITLE
A Visitor for creating a Target element that handles the conversion of regression results from `double` value space to `integer` value space

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-model#8]
Several PMML producers (eg. KNIME, Pervasive DataRush) are known to produce PMML documents where a `double` result is directly assigned to `integer` target field:

``` xml
<DataDictionary>
  <DataField name="myResult" dataType="integer"/>
</DataDictionary>
<RegressionModel functionName="regression">
  <MiningSchema>
    <MiningField name="myResult" usageType="target"/>
  </MiningSchema>
</RegressionModel>
```

The JPMML-Evaluator library rightfully throws a `TypeCheckException` when asked to evaluate such PMML documents:

```
Caused by: org.jpmml.evaluator.TypeCheckException: Expected INTEGER, but got DOUBLE (7.710705172582081)
        at org.jpmml.evaluator.TypeUtil.toInteger(TypeUtil.java:533)
        at org.jpmml.evaluator.TypeUtil.cast(TypeUtil.java:422)
        at org.jpmml.evaluator.TargetUtil.evaluateRegressionInternal(TargetUtil.java:86)
        at org.jpmml.evaluator.TargetUtil.evaluateRegression(TargetUtil.java:52)
        at org.jpmml.evaluator.RegressionModelEvaluator.evaluateRegression(RegressionModelEvaluator.java:100)
```

These PMML documents need to be corrected by introducing a `Target` element, which would make the conversion from `double` (or `float`) value space to `integer` value space explicit:

``` xml
<RegressionModel>
  <Targets>
    <Target field="myResult" castInteger="round"/>
  </Targets>
</RegressionModel>
```

This correction can be easily implemented using the Visitor approach. For maximal convenience, the JPMML-Model library should provide a default implementation, which could be applied by writing no more than two lines of application code:

``` java
Visitor corrector = new CastIntegerCorrector(Target.CastInteger.ROUND);
corrector.applyTo(pmml);
```

**Comment by vruusmann** [comment]
There's a related class `org.jpmml.knime.RegressionTargetCorrector` in the "pmml-knime" submodule of the JPMML-Evaluator project:
https://github.com/jpmml/jpmml-evaluator/commit/4b96ce7de30cdcfd6a9f76cdb59219b9cd0eb58c

It needs to be brought here, and refactored (eg. subclassing `org.jpmml.model.visitors.FieldResolver` for improved field lookup behaviour).

**Comment by vruusmann** [comment]
Won't fix. If some PMML producer software is known to produce invalid PMML markup, then it needs to be reported to the vendor of the said PMML producer software.

Soft-fixing at PMML consumer level simply does not scale.
